# Project Board Configuration
# This file defines the structure of the project board

# Project board name and description
name: "EduPath Development"
description: "Project board for tracking EduPath development tasks and features"

# Columns in the project board
columns:
  - name: "📋 Backlog"
    description: "Ideas and tasks that are ready to be worked on"
  - name: "🔍 To Do"
    description: "Tasks that are ready to be started"
  - name: "🚧 In Progress"
    description: "Tasks currently being worked on"
  - name: "🔍 Review/QA"
    description: "Tasks that need review or testing"
  - name: "✅ Done"
    description: "Completed tasks"

# Default labels for issues/PRs
labels:
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or improvement"
  - name: "documentation"
    color: "0075ca"
    description: "Documentation improvements"
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"
  - name: "priority: high"
    color: "b60205"
    description: "High priority task"
  - name: "priority: medium"
    color: "d93f0b"
    description: "Medium priority task"
  - name: "priority: low"
    color: "0e8a16"
    description: "Low priority task"
  - name: "status: blocked"
    color: "e99695"
    description: "Blocked by other work"
  - name: "status: in review"
    color: "d4c5f9"
    description: "Under review"
  - name: "type: bug"
    color: "d73a4a"
    description: "Bug fix"
  - name: "type: feature"
    color: "a2eeef"
    description: "New feature"
  - name: "type: refactor"
    color: "0052cc"
    description: "Code refactoring"
