version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: edupath
      POSTGRES_USER: edupath_user
      POSTGRES_PASSWORD: edupath_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  neo4j:
    image: neo4j:5.15
    environment:
      NEO4J_AUTH: neo4j/edupath_password
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://edupath_user:edupath_password@postgres:5432/edupath
      REDIS_URL: redis://redis:6379
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: edupath_password
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - postgres
      - redis
      - neo4j
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./edupath-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./edupath-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  neo4j_data:
